name: Test CI

on:
  push:
    branches:
      - develop

# force switching from Node.js 20 to Node.js 24 to avoid warning message
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test
        run: echo "Hello GitHub Actions"
