name: Build PDF

on:
  push:
    branches:
      - develop
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: debian:stable-slim

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y \
            texlive-latex-base --no-install-recommends \
            latexmk

      - name: Build
        run: |
          latexmk -pdf main.tex
